# Generated by Django 3.2 on 2021-04-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clubs', '0002_membership'),
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.AlterField(
                model_name='user',
                name='groups',
                field=models.ManyToManyField(blank=True,
                                             help_text='Группы к которым пренадлежит юзер. По ним определяется набор разрешений для юзера',
                                             related_name='user_set', related_query_name='user',
                                             through='clubs.Membership', to='auth.Group', verbose_name='Группы'),
            ),
        ])
    ]
