# Generated by Django 3.1.7 on 2021-03-25 15:35

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ваша арена, стадион, зал, каток.', max_length=64,
                                          verbose_name='Название локации')),
                ('description', models.CharField(max_length=1024, verbose_name='Краткое описание')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['club'])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.club')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
