version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8002:8000"
    volumes:
      - ./backend:/worker/app
      - ./reports:/worker/reports
    command: >
      sh -c "gunicorn --bind :8000 config.wsgi:application"
    env_file:
      - .docker/dev.env
      - .docker/db.env
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - .docker/db.env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - '5432'
