version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8002:8000"
    volumes:
      - ./crm:/app
    command: >
      sh -c "gunicorn --bind :8000 crm.wsgi:application"
    environment:
      - DB_HOST=db
      - DB_NAME=crm
      - DB_USER=postgres
      - DB_PASS=pass1
      - DJANGO_DATABASE=docker
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1