# Generated by Django 3.2 on 2021-04-30 08:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0005_auto_20210429_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('group', 'user', 'club')},
        ),
    ]
