# Generated by Django 3.2 on 2021-05-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_membership_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='club',
            name='employees',
        ),
    ]
