# Generated by Django 3.1.7 on 2021-03-31 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('login', models.CharField(blank=True,
                                           help_text='Ваш идентификатор, например, email или телефон, по которому вас зарегистрировали',
                                           max_length=150, unique=True, verbose_name='Логин')),
                ('phone', models.CharField(blank=True, help_text='+79871234567', max_length=12, null=True, unique=True,
                                           verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('is_staff',
                 models.BooleanField(default=False, help_text='Определяет, может ли юзер иметь доступ в суперадминку.',
                                     verbose_name='Технический Сотрудник сервиса')),
                ('is_active', models.BooleanField(default=True,
                                                  help_text='Отключает аккаунт вместо физического удаления из БД. Только Сотрудник сервиса может сделать вновь активным.',
                                                  verbose_name='Аккаунт активен')),
                ('date_joined',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания аккаунта')),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set', related_query_name='user', to='auth.Group',
                                                  verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                                            related_name='user_set', related_query_name='user',
                                                            to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
    ]
