# Generated by Django 3.2 on 2021-04-19 11:21

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='+79871234567', max_length=12, null=True, unique=True, validators=[common.validators.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
